before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: FRNxUDeTEY4+UkABK5tT/pH1uR3l5R0JKgW4k3/vxK4sCvURi3duxaXUSmkfE3fIE8lHDt50nsY0alQBm6JtRAZkc7Ygz+ryzob/LUWHZtD5mmWmksNVHndga24uJC8cWyLx88E4Y9elUjOHa9bHhYm65ZCpfW6HbXa2Tw6nyli3GnaOj0F04OwoNC2iEvRsthgYMZrBDpI9Sy78lCsO7c4UY85NzcuDYC1J6H0OLLvmuTmP0fUhOmOxkInU/IT6GBtse1horjPwrDxBD4eHJB2mC0gQ53nTbo6bLhy2vNAJjt4thH1AxZWCPA6fZH4mt/2XJwI0uo/O6+yU+/bvobSJ7fXsWIArBPSzCTlvGHd04mFvytxevAX24hGVDmqN4BrEUnUo/NfEA68iD7cVVRKfN3RUdEnEpX48qLx3iB997hn2RJiFeLM+7VZjcwN5JiTRnKYid4dPtksh1QV2OEpI6sAshR624X0Sf26d4xScx3w9I1LSwkIovF7jNnIK+gCCe2fkn99fd/hmDQYDicPXahPRWYh+c+V8lI7pC6zRtTeRVE2PTP7sp8KGX2/f/sfPXiRavlJ0G3yW37l43avLkQh7R68/oiC+T/LRJwQfaZ0VTpSg45fdVVe6IKU4eyhyG6hKX9JYNwrj3myNFqfFWGtWPoBM/Vy8/egSSuM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
